# 1.Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [4]:
matrix1=np.matrix([1,2,4,6,6,8,9,9,9,10]).reshape(5,2)

In [7]:
matrix1

matrix([[ 1,  2],
        [ 4,  6],
        [ 6,  8],
        [ 9,  9],
        [ 9, 10]])

In [5]:
matrix2=np.matrix([34,5,35,453,3,6,4,35,342,24]).reshape(5,2)

In [8]:
matrix2

matrix([[ 34,   5],
        [ 35, 453],
        [  3,   6],
        [  4,  35],
        [342,  24]])

In [9]:
matrix1+matrix2

matrix([[ 35,   7],
        [ 39, 459],
        [  9,  14],
        [ 13,  44],
        [351,  34]])

# 2. Write a Python Program to Multiply Two Matrices?

In [20]:
m1=np.matrix([2,5,6,8,4,8]).reshape(3,2)

In [21]:
m1

matrix([[2, 5],
        [6, 8],
        [4, 8]])

In [22]:
m2=np.matrix([3,5,7,3,1,6]).reshape(2,3)

In [23]:
m2

matrix([[3, 5, 7],
        [3, 1, 6]])

In [19]:
m1@m2 

matrix([[21, 15, 44],
        [42, 38, 90],
        [36, 28, 76]])

# 3. Write a Python Program to Transpose a Matrix?

In [25]:
m3=np.matrix([1,2,4,6,4,3,3,8,2,10,4,31]).reshape(2,6)

In [26]:
m3

matrix([[ 1,  2,  4,  6,  4,  3],
        [ 3,  8,  2, 10,  4, 31]])

In [27]:
m3=m3.T

In [28]:
m3

matrix([[ 1,  3],
        [ 2,  8],
        [ 4,  2],
        [ 6, 10],
        [ 4,  4],
        [ 3, 31]])

# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [29]:
text='Hello my name is Akshay'

In [30]:
words=text.split()

In [31]:
words

['Hello', 'my', 'name', 'is', 'Akshay']

In [37]:
lower=[]
for i in words:
  lower.append(i.lower())

In [38]:
lower

['hello', 'my', 'name', 'is', 'akshay']

In [41]:
lower.sort() #by default ascending

In [40]:
lower

['akshay', 'hello', 'is', 'my', 'name']

In [45]:
lower.sort(reverse=True)

In [46]:
lower

['name', 'my', 'is', 'hello', 'akshay']

# 5. Write a Python Program to Remove Punctuation From a String?

In [47]:
string='welcome to Bengaluru!, how are you doing?.'

In [49]:
punctuation='/','.','?',','

cleantext=''
for i in string:
  if i not in punctuation:
    cleantext=cleantext+i
print(cleantext)

welcome to Bengaluru how are you doing
